-- ─────────────────────────────────────────────────────────────────────────────
-- Growth Engine — Supabase schema
-- Run this once in the Supabase dashboard: SQL Editor → New query → paste → Run.
-- It creates the tables the app reads live, with public (anon) READ access only.
-- Writes are reserved for the service_role key (used by the daily refresh job),
-- so the public site can never modify data.
-- ─────────────────────────────────────────────────────────────────────────────

-- 1) NEWS ─ the live news desk (the daily routine writes here; the app reads it)
create table if not exists public.news (
  id           text primary key,
  published_at date not null default current_date,
  date_label   text,                 -- e.g. "1 Jul 2026 · in effect"
  source       text,
  tone         text check (tone in ('tailwind','headwind','watch')),
  title        text not null,
  what         text,
  why          jsonb default '[]'::jsonb,   -- transmission chain: array of short steps
  impact       text,
  tags         jsonb default '[]'::jsonb,
  graph_origin text,                 -- causal-graph node id the event hits first
  graph_dir    int  default 1,       -- +1 origin rises, -1 falls
  graph_verb   text,                 -- e.g. "Trace oil's collapse"
  implications jsonb default '[]'::jsonb,   -- [{theme, dir:'up'|'down', note}]
  sort         int  default 0,       -- display order (higher = first)
  created_at   timestamptz default now()
);

-- 2) RELEASES ─ the economic calendar (previous / consensus / actual → surprise)
create table if not exists public.releases (
  id          text primary key,
  name        text not null,
  agency      text,
  release_at  date not null,
  period      text,
  previous    text,
  consensus   text,
  actual      text,                  -- null until the print lands
  node        text,                  -- graph node the release maps to
  importance  text default 'med',
  watch       text,
  hi          jsonb,                 -- {label, dir, note} for an upside surprise
  lo          jsonb,                 -- {label, dir, note} for a downside surprise
  created_at  timestamptz default now()
);

-- 3) NOWCASTS ─ where the future ML/prediction layer will write its forecasts
create table if not exists public.nowcasts (
  id          bigint generated by default as identity primary key,
  target      text not null,         -- e.g. 'cpi_yoy', 'zar_usd', 'gdp_qoq'
  horizon     text,                  -- e.g. 'next_print', '1w', '1m'
  point       numeric,               -- central estimate
  lo95        numeric,               -- lower 95% bound
  hi95        numeric,               -- upper 95% bound
  as_of       timestamptz default now(),
  model       text,                  -- e.g. 'lightgbm-v1', 'baseline-arimax'
  notes       text
);

-- ── Row-Level Security: public can READ, only service_role can WRITE ──────────
alter table public.news     enable row level security;
alter table public.releases enable row level security;
alter table public.nowcasts enable row level security;

drop policy if exists "public read news"     on public.news;
drop policy if exists "public read releases" on public.releases;
drop policy if exists "public read nowcasts" on public.nowcasts;

create policy "public read news"     on public.news     for select using (true);
create policy "public read releases" on public.releases for select using (true);
create policy "public read nowcasts" on public.nowcasts for select using (true);
-- (No insert/update/delete policy for anon → writes require the service_role key.)
