// ─────────────────────────────────────────────────────────────────────────────
// EIOS FINANCIAL-MARKETS BLUEPRINT — a faithful transcription of the three
// structured deliverables the Global Financial Markets brief ordered, for all ten
// market types: (1) the market-overview matrix, (2) the cross-market comparison,
// and (3) the per-market EIOS modelling blueprint. Reference knowledge, condensed.
// ─────────────────────────────────────────────────────────────────────────────

export const EIOS_MARKETS = [
  {
    id: "equities", name: "Equities",
    summary: "Transparent and continuously priced, but fragmented across exchanges, ATSs and off-exchange venues.",
    structure: "Central limit order books + auctions + wholesalers/ATSs; CCP cleared, CSD settled; closing auctions often anchor benchmarks.",
    liquidity: "Deep in index names, thinner in small caps. Watch spread, depth, slippage, auction imbalance.",
    participants: "Asset managers, retail brokers, market makers, wholesalers, HFT/PTFs, issuers.",
    linkages: "ETFs, index futures/options, financing, buybacks, credit spreads.",
    cmp: { transparency: "High (routing medium)", counterparty: "Low after CCP", holding: "intraday–years", regulation: "High", latency: "Very high", mtm: "High" },
    bp: {
      models: "Intraday state-space microstructure; factor models; jump-diffusion / stochastic vol",
      state: "Midprice, spread, depth, imbalance, auction indicators, factor betas, borrow cost",
      process: "Hawkes / order-flow intraday; Heston / Bates / GARCH daily",
      data: "Tick & order-book, auction files, corporate actions; intraday to 1y",
      stress: "Gap opens, volatility halts, spread blowouts, ETF-flow shocks",
      controls: "Stale-quote filters, venue harmonisation, odd-lot handling, corporate-action challenger",
    },
  },
  {
    id: "bonds", name: "Bonds",
    summary: "Vast, heterogeneous dealer market; liquidity is episodic and benchmark-dependent.",
    structure: "Mostly OTC dealer-intermediated; TRACE/EMMA add post-trade transparency; sovereign clearing & settlement vary.",
    liquidity: "Lower immediacy than equities. Watch bid-ask, turnover, quote dispersion, dealer inventory, repo specialness.",
    participants: "Sovereigns, corporates, dealers, banks, insurers, pensions, central banks.",
    linkages: "Core collateral for repo, rates curves, credit-spread transmission.",
    cmp: { transparency: "Medium (higher post-trade)", counterparty: "Medium OTC / lower if cleared", holding: "days–years", regulation: "High", latency: "Medium", mtm: "Medium" },
    bp: {
      models: "Curve-plus-spread decomposition; affine term structure; liquidity-adjusted credit",
      state: "OIS curve, sovereign curve, Z-spread/OAS, repo specialness, fail rates, issue age",
      process: "Multi-factor affine Gaussian / CIR; jump-to-default for credit",
      data: "TRACE/EMMA, sovereign quotes, repo, issuance; daily to 5y",
      stress: "Bear steepener, dash-for-cash, downgrade wave, clearing/margin change",
      controls: "Benchmark-mismatch controls, matrix-pricing challenger, quote-dispersion limits",
    },
  },
  {
    id: "fx", name: "FX",
    summary: "Largest global market, predominantly OTC, with swaps and forwards central to funding and hedging.",
    structure: "Dealer platforms, ECNs, voice, prime brokerage; spot/forwards/swaps/options; PvP settlement crucial where available.",
    liquidity: "Very deep in majors, thinner in EM/options. Watch spread, depth, last-look impact, basis, settlement mode.",
    participants: "Global banks, hedge funds, asset managers, corporates, central banks, PTFs.",
    linkages: "Connects all international assets via hedging, funding, carry and basis.",
    cmp: { transparency: "Medium pre / low-med OTC", counterparty: "Medium; settlement risk critical", holding: "intraday–months", regulation: "High", latency: "Very high", mtm: "High majors / lower others" },
    bp: {
      models: "Joint spot–forward–basis system; carry & flow models; realized/implied vol surfaces",
      state: "Spot, forwards, cross-currency basis, rate differentials, reserve & flow variables",
      process: "Local-stochastic vol or jump-diffusion; regime-switching carry",
      data: "Spot/forward ticks, fixings, option vols, rates; intraday to 2y",
      stress: "Dollar squeeze, EM sudden stop, fixing disruption, non-PvP settlement failure",
      controls: "Benchmark-variance checks, venue-fragmentation controls, fix-vs-live comparison",
    },
  },
  {
    id: "commodities", name: "Commodities",
    summary: "Price discovery is often futures-led but anchored to physical supply chains and inventories.",
    structure: "Futures/options on exchanges plus OTC physical & bespoke hedges; some deliver, some cash-settle.",
    liquidity: "Front months and benchmarks deepest. Watch roll liquidity, convenience yield, storage optionality.",
    participants: "Producers, merchants, consumers, CTAs, dealers, airlines, utilities.",
    linkages: "Inflation, FX, rates, shipping, geopolitics, collateral and basis.",
    cmp: { transparency: "Medium", counterparty: "Low listed / medium OTC", holding: "days–years", regulation: "High", latency: "High (benchmarks)", mtm: "Medium–high" },
    bp: {
      models: "Cost-of-carry & inventory models; seasonality / term-structure models",
      state: "Spot/futures curve, inventory, convenience yield, freight/storage, weather/policy",
      process: "Schwartz–Smith two-factor; jump diffusion; weather/event overlays",
      data: "Futures curves, inventory series, shipping, weather; daily to 3y",
      stress: "Supply outage, storage squeeze, sanctions, roll dislocation",
      controls: "Delivery-option challenger, location-grade basis validation",
    },
  },
  {
    id: "derivatives", name: "Derivatives (futures & options)",
    summary: "The most efficient standardized risk-transfer layer; listed is transparent, OTC is customizable.",
    structure: "Listed futures/options with CCPs; swaps & custom options OTC with clearing mandates where applicable.",
    liquidity: "Listed deep in benchmarks, OTC deep in customization. Watch open interest, surface density, margin liquidity.",
    participants: "Hedgers, dealers, asset managers, corporates, CTAs, funds.",
    linkages: "Main conduit for leverage, convexity, margin spirals, basis, cross-market hedging.",
    cmp: { transparency: "High", counterparty: "Low after CCP; margin risk high", holding: "intraday–months", regulation: "Very high", latency: "Very high", mtm: "High" },
    bp: {
      models: "Surface engines + CCP-aware margin simulators; exposure graphs for OTC",
      state: "Futures basis, option surfaces, margin, collateral, CSA terms, netting sets",
      process: "Local vol / SABR / LMM; Monte-Carlo exposure; stress-grid margin",
      data: "Exchange & SDR/TR data, margin files, sensitivities; intraday to maturity",
      stress: "Vol spike, basis gap, CCP margin procyclicality, wrong-way credit",
      controls: "No-arbitrage surface checks, independent price verification, collateral-disputes tracker",
    },
  },
  {
    id: "etfs", name: "ETFs & ETPs",
    summary: "A wrapper that adds intraday tradability and a two-layer liquidity system.",
    structure: "Exchange-traded secondary market + AP-led primary creation/redemption; varies by underlying.",
    liquidity: "Often more liquid than constituents intraday, but AP- and basket-dependent. Watch premium/discount, tracking difference.",
    participants: "Sponsors, APs, market makers, exchanges, end-investors.",
    linkages: "A bridge between cash markets and tactical allocation flows; can lead price discovery when the underlying is illiquid.",
    cmp: { transparency: "High wrapper / variable look-through", counterparty: "Low fund-share; AP dependence", holding: "intraday–years", regulation: "High", latency: "High", mtm: "High liquid / lower opaque" },
    bp: {
      models: "Basket / NAV arbitrage & premium-discount models",
      state: "iNAV/NAV, basket liquidity, AP concentration, fund flow, constituent liquidity",
      process: "State-space premium/discount; flow-impact models",
      data: "Holdings, basket files, AP activity, exchange data; intraday to quarterly",
      stress: "AP withdrawal, bond-ETF discount, creation-basket illiquidity",
      controls: "Constituent look-through, wrapper-vs-underlying challenger",
    },
  },
  {
    id: "money", name: "Money markets",
    summary: "Core plumbing for policy transmission, collateral pricing and short-term funding.",
    structure: "Fed funds / repo / CP / bills / MMFs / RRP; benchmark methodologies are policy-critical.",
    liquidity: "High in normal times, can gap at quarter-end or in stress. Watch repo specials, MMF flows, CP tiering.",
    participants: "Banks, MMFs, dealers, GSEs, central banks, corporates.",
    linkages: "Drives discounting, collateral value, leverage capacity, stablecoin-reserve transmission.",
    cmp: { transparency: "High official / mixed bilateral", counterparty: "Medium; funding roll risk", holding: "overnight–months", regulation: "Very high", latency: "Medium", mtm: "High (official rates)" },
    bp: {
      models: "Policy-rate corridor & secured/unsecured funding-network models",
      state: "EFFR, SOFR, OBFR, BGCR, ON-RRP usage, MMF flows, CP spreads",
      process: "Network liquidity models; mean-reverting spread models",
      data: "Central-bank rate files, repo, CP, MMF holdings/flows; daily to 1y",
      stress: "Quarter-end, reserve scarcity, CP freeze, MMF run",
      controls: "Benchmark-methodology lock, publication-lag monitor, floor/ceiling consistency",
    },
  },
  {
    id: "crypto", name: "Cryptocurrencies",
    summary: "Fragmented hybrid market where benchmark design and exchange quality are part of the asset.",
    structure: "Spot exchanges, DeFi venues, OTC desks, regulated futures/options; benchmark administrators critical.",
    liquidity: "Concentrated in major tokens and stablecoin pairs. Watch fragmentation, basis, funding, venue-outage risk.",
    participants: "Exchanges, market makers, miners/validators, retail, hedge funds, stablecoin issuers.",
    linkages: "Money markets (reserves), derivatives (basis/funding), and risk sentiment.",
    cmp: { transparency: "Low / fragmented", counterparty: "Venue / custody / stablecoin risk", holding: "minutes–months", regulation: "Uneven", latency: "Very high", mtm: "Variable" },
    bp: {
      models: "Venue-aggregated benchmark, basis/funding/liquidation models, on-chain flow analytics",
      state: "Benchmark index, perp funding, stablecoin supply/composition, basis, liquidations",
      process: "Jump-diffusion with regime switches; agent-based liquidation overlays",
      data: "Exchange trades, order books, on-chain, benchmark; seconds to 1y",
      stress: "Stablecoin depeg, venue outage, liquidation cascade, custody/regulatory shock",
      controls: "Exchange-reliability score, benchmark-constituent controls, wash-trade screens",
    },
  },
  {
    id: "vol", name: "Volatility markets",
    summary: "A second-order market on expected or realized variance — hedging convexity and tail risk.",
    structure: "Index methodology + futures/options/variance products; settlement via option-based special quotations.",
    liquidity: "Good in benchmark indices, thinner in the wings and long tails. Watch skew and term-structure liquidity.",
    participants: "Dealers, structured-product desks, macro funds, vol funds, hedgers.",
    linkages: "Strongly linked to equities, rates, credit and systematic de-risking.",
    cmp: { transparency: "High benchmarks / thin tails", counterparty: "Low after CCP; convexity risk", holding: "intraday–months", regulation: "High", latency: "Very high", mtm: "Medium–high" },
    bp: {
      models: "Surface factorization, vol-of-vol, forward-variance extraction",
      state: "Term structure, skew, convexity, VVIX-style vol-of-vol, settlement pin risk",
      process: "Rough vol / Heston / SABR; forward-variance curves",
      data: "Option chains, settlement specs, realized vol; intraday to 2y",
      stress: "Short-gamma cascade, SOQ gap, skew inversion",
      controls: "Static-arbitrage tests, settlement-window challenger",
    },
  },
  {
    id: "alts", name: "Alternative assets",
    summary: "Economically important but least transparent, slowest to mark, hardest to aggregate.",
    structure: "Closed-end / bespoke structures, subscription lines, bilateral lending, appraisals, fund administrators.",
    liquidity: "Reported vol understates economic vol. Watch pacing, secondary discounts, cash-flow timing.",
    participants: "GPs, LPs, private-credit funds, PE sponsors, insurers, family offices.",
    linkages: "Bank & insurer balance sheets, public-market exits, refinancing conditions.",
    cmp: { transparency: "Low", counterparty: "Medium–high (structure/leverage)", holding: "years", regulation: "Medium–high (heterogeneous)", latency: "Low pricing / high event", mtm: "Low–medium" },
    bp: {
      models: "Latent-value & cash-flow pacing; credit migration & default for private credit",
      state: "NAV lag, cash-flow schedule, leverage, covenant dispersion, secondary discounts",
      process: "Bayesian latent-state, hazard/default, appraisal-smoothing adjustment",
      data: "Administrator, GP/LP reports, deal terms, appraisal data; quarterly to 10y",
      stress: "Exit drought, refinancing wall, secondary markdown, subscription-line withdrawal",
      controls: "Stale-price penalties, independent valuation committee, look-through thresholds",
    },
  },
];

export const CMP_COLUMNS = [
  { k: "transparency", label: "Transparency" },
  { k: "counterparty", label: "Counterparty risk" },
  { k: "holding", label: "Holding period" },
  { k: "regulation", label: "Regulation" },
  { k: "latency", label: "Latency" },
  { k: "mtm", label: "Mark-to-market" },
];

export const EIOS_NOTE =
  "The financial-markets brief's three structured deliverables — market overview, cross-market comparison, and per-market modelling blueprint — transcribed for reference. Descriptions of institutional practice; this app doesn't run these engines or carry their data.";
