// Generates supabase/seed.sql from the app's built-in config, so the Supabase
// tables can be populated with the current news + calendar in one paste.
// Run: node scripts/gen-seed.mjs
import { writeFileSync } from "node:fs";
import { NEWS, NEWS_GRAPH, IMPLICATIONS } from "../src/config/news.js";
import { RELEASES } from "../src/config/calendar.js";

const s = (v) => (v == null ? "null" : "'" + String(v).replace(/'/g, "''") + "'");
const j = (v) => "'" + JSON.stringify(v ?? null).replace(/'/g, "''") + "'::jsonb";
const n = (v) => (v == null ? "null" : Number(v));

const lines = [];
lines.push("-- AUTO-GENERATED by scripts/gen-seed.mjs — the current news + calendar.");
lines.push("-- Run in the Supabase SQL Editor AFTER schema.sql. Idempotent (upserts).");
lines.push("");

// NEWS
NEWS.forEach((story, i) => {
  const g = NEWS_GRAPH[story.id] ?? {};
  const impl = IMPLICATIONS[story.id] ?? [];
  const sort = NEWS.length - i; // preserve display order (first = highest)
  lines.push(
    `insert into public.news (id, date_label, source, tone, title, what, why, impact, tags, graph_origin, graph_dir, graph_verb, implications, sort) values (` +
      `${s(story.id)}, ${s(story.date)}, ${s(story.source)}, ${s(story.tone)}, ${s(story.title)}, ${s(story.what)}, ${j(story.why)}, ${s(story.impact)}, ${j(story.tags)}, ${s(g.origin)}, ${n(g.dir ?? 1)}, ${s(g.verb)}, ${j(impl)}, ${sort})` +
      ` on conflict (id) do update set date_label=excluded.date_label, source=excluded.source, tone=excluded.tone, title=excluded.title, what=excluded.what, why=excluded.why, impact=excluded.impact, tags=excluded.tags, graph_origin=excluded.graph_origin, graph_dir=excluded.graph_dir, graph_verb=excluded.graph_verb, implications=excluded.implications, sort=excluded.sort;`
  );
});
lines.push("");

// RELEASES
RELEASES.forEach((r) => {
  lines.push(
    `insert into public.releases (id, name, agency, release_at, period, previous, consensus, node, importance, watch, hi, lo) values (` +
      `${s(r.id)}, ${s(r.name)}, ${s(r.agency)}, ${s(r.iso)}, ${s(r.period)}, ${s(r.previous)}, ${s(r.consensus)}, ${s(r.node)}, ${s(r.importance)}, ${s(r.watch)}, ${j(r.hi)}, ${j(r.lo)})` +
      ` on conflict (id) do update set name=excluded.name, agency=excluded.agency, release_at=excluded.release_at, period=excluded.period, previous=excluded.previous, consensus=excluded.consensus, node=excluded.node, importance=excluded.importance, watch=excluded.watch, hi=excluded.hi, lo=excluded.lo;`
  );
});
lines.push("");

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), lines.join("\n"));
console.log(`Wrote supabase/seed.sql — ${NEWS.length} news rows, ${RELEASES.length} releases.`);
